name: MinGW Win32 CI

on: [push]

jobs:
  buildgcc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup msys2
        uses: numworks/setup-msys2@v1
        with:
          msystem: MINGW32
      - name: mingw update 
        run: |
           msys2do pacman -S --noconfirm --needed base-devel mingw-w64-i686-toolchain make perl nasm
           msys2do wget http://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz
           msys2do wget http://repo.msys2.org/mingw/i686/mingw-w64-i686-winpthreads-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz

           msys2do pacman -U --noconfirm mingw-w64-i686-libwinpthread-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz mingw-w64-i686-winpthreads-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz

           msys2do rm mingw-w64-i686-libwinpthread-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz
           msys2do rm mingw-w64-i686-winpthreads-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz
      - name: mingw build
        run : msys2do make mingw510 -j9 RELEASEBUILD=1
      - name: make artifacts
        run: |
           mkdir fbn-x86-gcc
           cd fbn-x86-gcc
           cp ../fbneo.exe .
           cp ../fba.chm .
           cp ../*.zip .
           cp ../src/license.txt .
           cp ../whatsnew.html .
      - name: upload gcc x86 artifacts
        uses: actions/upload-artifact@v1
        with:
          name: fbn-x86-gcc
          path: fbn-x86-gcc    
